name: MSBuild
on:
  push:
    branches: [ "main", "actions" ]
  pull_request:
    branches: [ "main", "actions" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  
permissions:
  contents: read
jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest


    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: vcpkg build
        id: vcpkg
        uses: johnwason/vcpkg-action@v5
        with:
          manifest-dir: ${{ github.workspace }}/AsaApiLoader # Set to directory containing vcpkg.json
          triplet: x64-windows-release
          token: ${{ github.token }}

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
  
      - name: Restore vcpkg packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: vcpkg integrate install

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}

        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
