name: MSBuild
on:
  push:
    branches: [ "main", "actions" ]
  pull_request:
    branches: [ "main", "actions" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  
permissions:
  contents: read
jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest


    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Restore Packages
        working-directory: ${{env.SOLUTION_FILE_PATH}}/AsaApiLoader
        run: vcpkg install --triplet=x64-windows-static-md --x-install-root=vcpkg_installed\x64-windows-static-md

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

      - uses: actions/upload-artifact@v3
        with:
          name: Upload EXE
          path: ${{env.SOLUTION_FILE_PATH}}/x64/Debug/AsaApiLoader.exe

      - uses: actions/upload-artifact@v3
        with:
          name: Upload PDB
          path: ${{env.SOLUTION_FILE_PATH}}/x64/Debug/AsaApiLoader.pdb
