name: PublishBinary
on:
  push:
    branches: [ "main", "actions" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  
permissions:
  contents: read
jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest


    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Restore vcpkg
        working-directory: ${{env.SOLUTION_FILE_PATH}}/AsaApiLoader
        run: vcpkg install --triplet=x64-windows-static-md --x-install-root=vcpkg_installed\x64-windows-static-md

      - name: Integrate vcpkg
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: vcpkg integrate install

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

      - uses: actions/upload-artifact@v3
        with:
          name: AsaApiLoader
          path: ${{env.SOLUTION_FILE_PATH}}/x64/Release/

      - name: Lastest Auto-Build
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{env.SOLUTION_FILE_PATH}}/x64/Release/AsaApiLoader.exe
            ${{env.SOLUTION_FILE_PATH}}/x64/Release/AsaApiLoader.pdb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
